export const mockInterviews = {
  google: {
    name: 'Google Interviewer',
    abbr: 'G',
    color: '#4285F4',
    style: 'Technical and analytical',
    tone: 'Formal and probing',
    focusAreas: ['Problem-solving', 'System design', 'Technical depth', 'Coding fundamentals'],
    questions: [
      'Tell me about a time you solved a complex technical problem at scale.',
      'How would you design a URL shortener system like Bitly?',
      'Given an array of integers, find the longest subarray with sum equal to zero.',
      'How do you handle ambiguity in requirements during a project?',
      'Explain a time you had to make a trade-off between speed and quality.',
    ],
  },
  amazon: {
    name: 'Amazon Interviewer',
    abbr: 'A',
    color: '#FF9900',
    style: 'Leadership principles and behavioral',
    tone: 'Direct and structured',
    focusAreas: ['Leadership principles', 'Customer obsession', 'Ownership', 'Delivering results'],
    questions: [
      'Tell me about a time you disagreed with your manager. How did you handle it?',
      'Describe a situation where you took ownership of a project and delivered results.',
      'How do you prioritize when you have multiple competing deadlines?',
      'Tell me about a time you failed and what you learned from it.',
      'How do you ensure customer satisfaction in a product you own?',
    ],
  },
  meta: {
    name: 'Meta Interviewer',
    abbr: 'M',
    color: '#1877F2',
    style: 'Fast-paced and product-oriented',
    tone: 'Casual but probing',
    focusAreas: ['Product sense', 'System design', 'Coding', 'Impact and growth'],
    questions: [
      'How would you measure the success of a new Facebook feature?',
      'Design the news feed algorithm for a social media platform.',
      'Given a list of intervals, merge all overlapping intervals.',
      'How would you approach building a feature that increases user engagement by 10%?',
      'Tell me about a time you had to make a decision with incomplete data.',
    ],
  },
  microsoft: {
    name: 'Microsoft Interviewer',
    abbr: 'MS',
    color: '#00A4EF',
    style: 'Growth mindset and collaborative',
    tone: 'Thoughtful and collaborative',
    focusAreas: ['Growth mindset', 'Collaboration', 'Technical skills', 'Mission alignment'],
    questions: [
      'How do you foster collaboration in a cross-functional team?',
      'Describe a time you had to learn a new technology quickly to solve a problem.',
      'How would you design a caching layer for a high-traffic web application?',
      'Tell me about a time you received negative feedback and how you responded.',
      'How do you balance innovation with stability in a product?',
    ],
  },
};
