export const mockInterviews = {
  google: {
    name: 'Google Interviewer',
    abbr: 'G',
    color: '#4285F4',
    style: 'Technical and analytical',
    tone: 'Formal and probing',
    focusAreas: ['Problem-solving', 'System design', 'Technical depth', 'Coding fundamentals'],
    questions: [
      'Tell me about a time you solved a complex technical problem at scale.',
      'How would you design a URL shortener system like Bitly?',
      'Given an array of integers, find the longest subarray with sum equal to zero.',
      'How do you handle ambiguity in requirements during a project?',
      'Explain a time you had to make a trade-off between speed and quality.',
      'Design a distributed system that can handle millions of concurrent users.',
      'How would you optimize a slow database query in a web application?',
      'Describe a time when you had to debug a production issue under pressure.',
      'How do you approach testing and ensuring the reliability of your code?',
      'Tell me about a time you had to learn a new technology stack quickly for a project.',
      'How would you design a notification system that can send millions of notifications per minute?',
      'Explain the difference between consistency and availability in distributed systems.',
      'How do you handle technical debt in a fast-moving development environment?',
      'Describe a situation where you had to present a technical solution to a non-technical audience.',
      'What steps would you take to secure a web application from common vulnerabilities?',
      'How would you implement a rate limiter for an API?',
      'Tell me about a time you had to refactor a large codebase. What was your approach?',
      'How do you ensure your code is maintainable and readable by other developers?',
      'Design a system to store and retrieve user-generated content at scale.',
      'How would you handle data consistency in a microservices architecture?',
      'Tell me about a time you had to make an important technical decision with limited data.',
      'How would you approach debugging a memory leak in a production system?',
      'Explain how you would design a system to handle real-time analytics at scale.',
      'How do you approach performance optimization in a large codebase?',
      'Describe a time when you had to choose between a quick fix and a proper solution.',
      'How would you design a recommendation system for a large-scale platform?',
      'Tell me about a time you had to work with a legacy system. How did you handle it.',
      'How do you approach code reviews and what feedback do you typically give?',
      'Explain the concept of eventual consistency and when it might be appropriate.',
      'How would you design a system to handle traffic spikes without downtime?',
      'Describe a time when you had to estimate the scope of a complex technical project.',
      'How do you approach capacity planning for a new service?',
      'Tell me about a time you had to balance multiple technical priorities simultaneously.',
      'How would you design a system to handle sensitive user data securely?',
      'Explain how you would approach building a highly available system.',
      'How do you stay current with new technologies and industry trends?',
      'Describe a time when you had to make a technical decision that conflicted with business goals.',
      'How would you approach designing a scalable caching strategy?',
      'Tell me about a time you had to migrate a production system with zero downtime.',
      'How do you handle disagreements about technical architecture within your team?',
      'How would you design a system to support multiple data centers?',
      'Describe a situation where you had to choose the right tool or technology for a job.',
      'How do you approach writing automated tests for complex systems?',
      'Tell me about a time you had to troubleshoot a difficult performance issue.',
      'How would you design a system that processes and stores streaming data?',
      'Explain how you would approach technical debt measurement and prioritization.',
      'How do you handle situations where you don\'t have enough information to make a decision?',
      'Describe a time when you had to simplify a complex system without losing functionality.',
      'How would you design a system to support A/B testing at scale?',
      'Tell me about a time you had to balance security requirements with user experience.',
      'How do you approach debugging intermittent or hard-to-reproduce issues?',
      'How would you design a system to handle multi-tenancy?',
      'Describe a time when you had to advocate for a technical improvement with stakeholders.',
      'How do you approach choosing between building in-house versus buying a third-party solution?',
      'Tell me about a time you had to work under significant time pressure on a technical project.',
      'How would you design a system to handle real-time data processing and delivery?',
      'Explain your approach to database schema design for a new product.',
    ],
  },
  amazon: {
    name: 'Amazon Interviewer',
    abbr: 'A',
    color: '#FF9900',
    style: 'Leadership principles and behavioral',
    tone: 'Direct and structured',
    focusAreas: ['Leadership principles', 'Customer obsession', 'Ownership', 'Delivering results'],
    questions: [
      'Tell me about a time you disagreed with your manager. How did you handle it?',
      'Describe a situation where you took ownership of a project and delivered results.',
      'How do you prioritize when you have multiple competing deadlines?',
      'Tell me about a time you failed and what you learned from it.',
      'How do you ensure customer satisfaction in a product you own?',
      'Give me an example of when you had to influence someone without authority.',
      'Tell me about a time when you had to work with a difficult team member or stakeholder.',
      'How do you approach mentoring and developing junior team members?',
      'Describe a time when you had to make a decision that impacted the customer experience.',
      'Tell me about a time you had to deliver results with limited resources or support.',
      'How do you handle ambiguity when the path forward is unclear?',
      'Give me an example of when you demonstrated a bias for action in a difficult situation.',
      'Describe a situation where you had to simplify a complex problem for a broader audience.',
      'Tell me about a time when you had to adapt your communication style for different audiences.',
      'How do you ensure you are customer-obsessed in your daily work?',
      'Give me an example of when you went above and beyond for a customer.',
      'Describe a time when you had to make a short-term decision that conflicted with long-term goals.',
      'Tell me about a time you had to lead a team through a significant change.',
      'How do you approach conflict resolution within your team?',
      'Give me an example of when you had to make a difficult trade-off decision.',
      'Describe a situation where you identified a problem before it became critical.',
      'Tell me about a time when you had to learn and apply a new skill quickly.',
      'How do you approach setting goals and measuring success?',
      'Give me an example of when you had to make a decision with incomplete data.',
      'Tell me about a time you had to balance multiple priorities with conflicting deadlines.',
      'How do you handle underperforming team members on your project?',
      'Describe a time when you had to take a calculated risk on a project or idea.',
      'Tell me about a time when you had to deliver results with a constantly changing product scope.',
      'How do you ensure operational excellence in your team\'s deliverables?',
      'Give me an example of when you had to work overtime to meet a critical deadline.',
      'Describe a situation where you had to stand up for your beliefs despite opposition.',
      'Tell me about a time when you had to rebuild trust with a stakeholder or team.',
      'How do you approach decision-making when there is no clear right answer?',
      'Give me an example of when you had to manage a project with a distributed team.',
      'Tell me about a time when you had to advocate for a customer\'s needs within your organization.',
      'How do you handle situations where team members have different working styles?',
      'Describe a time when you had to prioritize customer needs over business objectives.',
      'Tell me about a time when you had to deliver difficult feedback to a high-performing team member.',
      'How do you approach building and maintaining relationships with cross-functional stakeholders?',
      'Give me an example of when you had to work with a team that had competing priorities.',
      'Describe a situation where you had to communicate a delay or setback to stakeholders.',
      'Tell me about a time when you had to make a decision that everyone disagreed with.',
      'How do you approach balancing innovation with execution?',
      'Give me an example of when you had to drive change within your organization.',
      'Tell me about a time when you had to take responsibility for a team failure.',
      'How do you handle situations where you need to deliver bad news to a customer?',
      'Describe a time when you had to work with limited or unclear direction.',
      'Tell me about a time when you had to make a decision that would impact future product development.',
    ],
  },
  meta: {
    name: 'Meta Interviewer',
    abbr: 'M',
    color: '#1877F2',
    style: 'Fast-paced and product-oriented',
    tone: 'Casual but probing',
    focusAreas: ['Product sense', 'System design', 'Coding', 'Impact and growth'],
    questions: [
      'How would you measure the success of a new Facebook feature?',
      'Design the news feed algorithm for a social media platform.',
      'Given a list of intervals, merge all overlapping intervals.',
      'How would you approach building a feature that increases user engagement by 10%?',
      'Tell me about a time you had to make a decision with incomplete data.',
      'How would you design a system to detect and remove fake accounts?',
      'What metrics would you use to measure the health of a social media platform?',
      'Design a real-time commenting system like Facebook Comments.',
      'How do you balance user privacy with personalization in product design?',
      'Tell me about a time you had to prioritize features for a product launch.',
      'How would you design a video streaming platform that scales globally?',
      'What is the difference between growth and engagement? How do you measure each?',
      'How would you approach A/B testing a new UI feature?',
      'Design a scalable system for storing and serving user photos.',
      'Tell me about a time you had to work with ambiguous product requirements.',
      'How would you handle a situation where a key metric is declining?',
      'Describe how you would design a messenger system for real-time communication.',
      'How do you ensure inclusivity and accessibility in Meta products?',
      'What would you do if you noticed a feature was causing user churn?',
      'How would you approach building a recommendation system for content?',
      'Describe a time when you had to make a product decision without data.',
      'How do you approach designing features for different global markets?',
      'Tell me about a time you had to advocate for a product direction your team didn\'t agree on.',
      'How would you design a notification system that doesn\'t overwhelm users?',
      'What is your approach to measuring the success of a new product feature?',
      'Describe a situation where you had to pivot a product based on user feedback.',
      'How do you balance short-term user satisfaction with long-term product vision?',
      'Tell me about a time you had to conduct competitive analysis for a new product.',
      'How would you approach pricing a new product or feature?',
      'Describe a time when you had to say no to a feature request from users.',
      'How do you ensure product-market fit when launching a new feature?',
      'Tell me about a time you had to work with data science teams to inform product decisions.',
      'How would you approach designing a product for emerging markets?',
      'Describe your approach to user research and how it informs product decisions.',
      'How do you handle situations where user feedback contradicts your product instincts?',
      'Tell me about a time you had to explain a product decision to executives.',
      'How would you approach building a product from scratch with limited resources?',
      'Describe a time when you had to handle a product crisis or outage.',
      'How do you approach feature prioritization in a fast-moving environment?',
      'Tell me about a time you had to work with external partners or API providers.',
      'How would you design a system to handle viral content?',
      'Describe your approach to onboarding and user retention for a new product.',
      'How do you measure and improve user engagement over time?',
      'Tell me about a time when you had to make a decision based on qualitative data.',
      'How would you approach designing a product for accessibility?',
      'Describe a time when you had to work with legal or compliance teams on a product.',
      'How do you ensure ethical design in your products?',
      'Tell me about a time when you had to handle a competitive product launch.',
      'How would you approach building a community feature?',
      'Describe your approach to growth hacking and user acquisition.',
      'How do you balance experimentation with consistency in product development?',
      'Tell me about a time you had to work with a rapidly scaling user base.',
      'How would you approach designing a product for international expansion?',
    ],
  },
  microsoft: {
    name: 'Microsoft Interviewer',
    abbr: 'MS',
    color: '#00A4EF',
    style: 'Growth mindset and collaborative',
    tone: 'Thoughtful and collaborative',
    focusAreas: ['Growth mindset', 'Collaboration', 'Technical skills', 'Mission alignment'],
    questions: [
      'How do you foster collaboration in a cross-functional team?',
      'Describe a time you had to learn a new technology quickly to solve a problem.',
      'How would you design a caching layer for a high-traffic web application?',
      'Tell me about a time you received negative feedback and how you responded.',
      'How do you balance innovation with stability in a product?',
      'Describe a time when you had to work with a difficult team member.',
      'How do you approach debugging a complex system issue?',
      'Tell me about a time you had to make a technical decision under time constraints.',
      'How do you ensure inclusive design in your products?',
      'Describe a situation where you had to explain a complex technical concept to a non-technical audience.',
      'How do you approach writing clean, maintainable code?',
      'Tell me about a time you had to refactor a legacy system.',
      'How would you design a system to handle real-time data processing?',
      'Describe your approach to code reviews and how you give feedback.',
      'How do you handle technical disagreements with your team?',
      'Tell me about a time you had to ship a product with known limitations.',
      'How do you stay current with emerging technologies?',
      'Describe a time when you had to optimize the performance of a slow application.',
      'How do you approach designing APIs that are easy to use and maintain?',
      'Tell me about a time you had to work with stakeholders to define requirements.',
      'How do you approach mentoring junior developers on your team?',
      'Describe a situation where you had to make a decision that affected multiple teams.',
      'Tell me about a time when you had to advocate for a technical improvement.',
      'How do you approach technical documentation and knowledge sharing?',
      'How do you handle situations where you don\'t agree with your manager\'s technical decisions?',
      'Describe a time when you had to work with a team that had different technical backgrounds.',
      'Tell me about a time when you had to balance technical excellence with delivery deadlines.',
      'How do you approach learning from production incidents?',
      'How would you design a resilient system that can recover from failures?',
      'Describe a time when you had to work with cloud infrastructure at scale.',
      'Tell me about a time when you had to make a trade-off between user experience and technical constraints.',
      'How do you approach building systems that can evolve over time?',
      'How do you handle situations where a project is behind schedule?',
      'Describe a time when you had to work with external vendors or partners.',
      'Tell me about a time when you had to simplify a complex technical architecture.',
      'How do you approach measuring technical quality in software development?',
      'How would you design a monitoring and alerting system for a distributed application?',
      'Describe a time when you had to work in an agile or scrum environment.',
      'Tell me about a time when you had to handle a major technical outage.',
      'How do you approach capacity planning for cloud-based applications?',
      'How do you ensure security is built into your development process?',
      'Describe a time when you had to work with a legacy codebase and modernize it.',
      'Tell me about a time when you had to make a decision about technical architecture.',
      'How do you approach technical leadership and influencing without authority?',
      'How would you design a system to handle multi-region deployments?',
      'Describe a time when you had to work with DevOps or SRE teams.',
      'Tell me about a time when you had to handle competing priorities from different stakeholders.',
      'How do you approach building a culture of experimentation in your team?',
      'How would you design a system to handle data privacy and compliance requirements?',
      'Describe a time when you had to work on a project with unclear or changing requirements.',
      'Tell me about a time when you had to make a difficult technical decision with significant business impact.',
      'How do you approach continuous improvement in your development practices?',
      'How would you design a system to support both new feature development and maintenance?',
      'Describe a time when you had to work with open-source software or contribute to open-source projects.',
    ],
  },
};

export const TOTAL_QUESTIONS = 5;

export function getRandomQuestions(companyQuestions) {
  const allQs = [...companyQuestions];
  for (let i = allQs.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [allQs[i], allQs[j]] = [allQs[j], allQs[i]];
  }
  return allQs.slice(0, TOTAL_QUESTIONS);
}
