export const mockInterviews = {
  google: {
    name: 'Google Interviewer',
    abbr: 'G',
    color: '#4285F4',
    style: 'Technical and analytical',
    tone: 'Formal and probing',
    focusAreas: ['Problem-solving', 'System design', 'Technical depth', 'Coding fundamentals'],
    questions: [
      'Tell me about a time you solved a complex technical problem at scale.',
      'How would you design a URL shortener system like Bitly?',
      'Given an array of integers, find the longest subarray with sum equal to zero.',
      'How do you handle ambiguity in requirements during a project?',
      'Explain a time you had to make a trade-off between speed and quality.',
      'Design a distributed system that can handle millions of concurrent users.',
      'How would you optimize a slow database query in a web application?',
      'Describe a time when you had to debug a production issue under pressure.',
      'How do you approach testing and ensuring the reliability of your code?',
      'Tell me about a time you had to learn a new technology stack quickly for a project.',
      'How would you design a notification system that can send millions of notifications per minute?',
      'Explain the difference between consistency and availability in distributed systems.',
      'How do you handle technical debt in a fast-moving development environment?',
      'Describe a situation where you had to present a technical solution to a non-technical audience.',
      'What steps would you take to secure a web application from common vulnerabilities?',
      'How would you implement a rate limiter for an API?',
      'Tell me about a time you had to refactor a large codebase. What was your approach?',
      'How do you ensure your code is maintainable and readable by other developers?',
      'Design a system to store and retrieve user-generated content at scale.',
      'How would you handle data consistency in a microservices architecture?',
    ],
  },
  amazon: {
    name: 'Amazon Interviewer',
    abbr: 'A',
    color: '#FF9900',
    style: 'Leadership principles and behavioral',
    tone: 'Direct and structured',
    focusAreas: ['Leadership principles', 'Customer obsession', 'Ownership', 'Delivering results'],
    questions: [
      'Tell me about a time you disagreed with your manager. How did you handle it?',
      'Describe a situation where you took ownership of a project and delivered results.',
      'How do you prioritize when you have multiple competing deadlines?',
      'Tell me about a time you failed and what you learned from it.',
      'How do you ensure customer satisfaction in a product you own?',
      'Give me an example of when you had to influence someone without authority.',
      'Tell me about a time you had to deliver results with limited resources.',
      'Describe a situation where you identified and solved a process improvement.',
      'How do you handle underperforming team members on your project?',
      'Tell me about a time when you had to make a decision with incomplete information.',
      'Give me an example of when you demonstrated dive deep into a problem.',
      'How do you handle conflicts within your team?',
      'Describe a time when you had to earn trust with a new team or stakeholder.',
      'Tell me about a time when you had to adapt to a significant change at work.',
      'How do you ensure you are customer-obsessed in your daily work?',
      'Give me an example of when you showed bias for action in a difficult situation.',
      'Describe a time when you had to think big and come up with a creative solution.',
      'How do you approach mentoring or developing other team members?',
      'Tell me about a time when you had to balance short-term results with long-term goals.',
      'How do you handle ambiguity and uncertainty in your work?',
    ],
  },
  meta: {
    name: 'Meta Interviewer',
    abbr: 'M',
    color: '#1877F2',
    style: 'Fast-paced and product-oriented',
    tone: 'Casual but probing',
    focusAreas: ['Product sense', 'System design', 'Coding', 'Impact and growth'],
    questions: [
      'How would you measure the success of a new Facebook feature?',
      'Design the news feed algorithm for a social media platform.',
      'Given a list of intervals, merge all overlapping intervals.',
      'How would you approach building a feature that increases user engagement by 10%?',
      'Tell me about a time you had to make a decision with incomplete data.',
      'How would you design a system to detect and remove fake accounts?',
      'What metrics would you use to measure the health of a social media platform?',
      'Design a real-time commenting system like Facebook Comments.',
      'How do you balance user privacy with personalization in product design?',
      'Tell me about a time you had to prioritize features for a product launch.',
      'How would you design a video streaming platform that scales globally?',
      'What is the difference between growth and engagement? How do you measure each?',
      'How would you approach A/B testing a new UI feature?',
      'Design a scalable system for storing and serving user photos.',
      'Tell me about a time you had to work with ambiguous product requirements.',
      'How would you handle a situation where a key metric is declining?',
      'Describe how you would design a messenger system for real-time communication.',
      'How do you ensure inclusivity and accessibility in Meta products?',
      'What would you do if you noticed a feature was causing user churn?',
      'How would you approach building a recommendation system for content?',
    ],
  },
  microsoft: {
    name: 'Microsoft Interviewer',
    abbr: 'MS',
    color: '#00A4EF',
    style: 'Growth mindset and collaborative',
    tone: 'Thoughtful and collaborative',
    focusAreas: ['Growth mindset', 'Collaboration', 'Technical skills', 'Mission alignment'],
    questions: [
      'How do you foster collaboration in a cross-functional team?',
      'Describe a time you had to learn a new technology quickly to solve a problem.',
      'How would you design a caching layer for a high-traffic web application?',
      'Tell me about a time you received negative feedback and how you responded.',
      'How do you balance innovation with stability in a product?',
      'Describe a time when you had to work with a difficult team member.',
      'How do you approach debugging a complex system issue?',
      'Tell me about a time you had to make a technical decision under time constraints.',
      'How do you ensure inclusive design in your products?',
      'Describe a situation where you had to explain a complex technical concept to a non-technical audience.',
      'How do you approach writing clean, maintainable code?',
      'Tell me about a time you had to refactor a legacy system.',
      'How would you design a system to handle real-time data processing?',
      'Describe your approach to code reviews and how you give feedback.',
      'How do you handle technical disagreements with your team?',
      'Tell me about a time you had to ship a product with known limitations.',
      'How do you stay current with emerging technologies?',
      'Describe a time when you had to optimize the performance of a slow application.',
      'How do you approach designing APIs that are easy to use and maintain?',
      'Tell me about a time you had to work with stakeholders to define requirements.',
    ],
  },
};

export const TOTAL_QUESTIONS = 5;

export function getRandomQuestions(companyQuestions) {
  const allQs = [...companyQuestions];
  const shuffled = allQs.sort(() => Math.random() - 0.5);
  return shuffled.slice(0, TOTAL_QUESTIONS);
}
